# Chapter 2: Introduction to NumPy

In [3]:
import numpy as np

In [5]:
np.__version__

'1.16.4'

In [6]:
np?

## 1. creating numpy arrays
### 1.1 create np array from python lists

In [8]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [10]:
np.array([3.14, 4, 2, 3]) 
#unlike python list, np array contains fiexed type
#upcast took place when types of elements are different

array([3.14, 4.  , 2.  , 3.  ])

In [11]:
np.array([1, 2, 3, 4], dtype='float32')
#use dtype keyword to manually upcast

array([1., 2., 3., 4.], dtype=float32)

In [12]:
np.array([range(i, i + 3) for i in [2, 3, 6]])
#np array support multidimensional arrays

array([[2, 3, 4],
       [3, 4, 5],
       [6, 7, 8]])

### 1.2 create arrays from scratch

In [14]:
np.zeros(10, dtype=int)
#create length-10 integer array filed with 0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones((3, 5), dtype=float)
#create 3*5 array filed with 1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.full((3, 5), 3.14)
#create 3*5 array filed with 3.14

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [19]:
np.arange(0, 20, 2)
#similar to Python range() function

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
np.linspace(0, 1, 5)
#array of 5 values evenly spaced between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
np.random.random((3, 3))
#random values filled 3*3 array

array([[0.29077008, 0.39084644, 0.16874001],
       [0.27124232, 0.46584313, 0.70745943],
       [0.9007378 , 0.37371361, 0.22395265]])

In [24]:
np.random.normal(0, 1, (3,3))
#mean = 0, sd = 1

array([[ 0.36375105,  0.72624993, -1.45006096],
       [ 0.66795521,  0.6333861 , -1.82896334],
       [-0.53676091, -0.49565083, -0.59752768]])

In [25]:
np.random.randint(0, 10, (3, 3))
#random integers in interval [0, 10)

array([[1, 2, 6],
       [0, 0, 5],
       [7, 1, 8]])

In [26]:
np.eye(3)
#3*3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.empty(3)
#empty array, length 3, value will be whatever is in that memory location

array([1., 1., 1.])

### 1.3 data types

In [28]:
#we can initialize data types with string or np datatype object
np.zeros(10, dtype = "int16")
np.zeros(10, dtype = np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

## 2. basics of np arrays
### 2.1 attributes

In [30]:
np.random.seed(0)

x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3, 4))
x3 = np.random.randint(10, size = (3, 4, 5))

Each array has 3 attributes

* ndim: number of dimensions

* shape: size of each dimension

* size: total size

In [32]:
print("x3 ndim", x3.ndim)
print("x3 shape", x3.shape)
print("x3 size", x3.size)

x3 ndim 3
x3 shape (3, 4, 5)
x3 size 60


* dtype means datatype

In [33]:
print("dtype", x3.dtype)

dtype int64


* itemsize: size in bytes of each element
* nbytes: total size of array

In [35]:
print("itemsize", x3.itemsize, "bytes")
print("nbytes", x3.nbytes, "bytes")

itemsize 8 bytes
nbytes 480 bytes


# 2.2 index

In [36]:
x1

array([5, 0, 3, 3, 7, 9])

In [37]:
x1[0]

5

In [38]:
x1[4]

7

In [39]:
x1[-1]

9

In [40]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [41]:
x2[0, 0]

3

In [42]:
x2[2, 0]

1

In [43]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [44]:
#np array has fixed type
#what if we pass in a different type
x1[0] = 3.1212
x1

array([3, 0, 3, 3, 7, 9])

### 2.3 slicing
* format: x[start:stop:step]
* if any attribute is unspecified, default start=0, stop=size of dimension, step=1

In [46]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
x[:5]

array([0, 1, 2, 3, 4])

In [48]:
x[5:]

array([5, 6, 7, 8, 9])

In [49]:
x[4:7]

array([4, 5, 6])

#### 2.3.1 for multidimensional arrays

In [50]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [51]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [52]:
x2[::3, :2]

array([[12,  5]])

In [55]:
x1[::3]

array([3, 3])

In [56]:
x1

array([3, 0, 3, 3, 7, 9])

In [57]:
x2[:, 0]
#use single column at left to access coulumn

array([12,  7,  1])

In [58]:
x2[0, :]
#single coulumn at right to access rows

array([12,  5,  2,  4])

#### 2.3.2 views

In [62]:
#array slice return views... its like an reference
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [65]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [67]:
x2_sub[0,0] = 99
print (x2_sub)

[[99  5]
 [ 7  6]]


In [68]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


#### 2.3.3 copies

In [69]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [70]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


#### 2.3.4 reshaping

In [72]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [73]:
x = np.array([1, 2, 3])
x.reshape((1,3))

array([[1, 2, 3]])

In [74]:
x[np.newaxis, :]

array([[1, 2, 3]])